apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: jumptotech-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: juzonb1r/jumptotech-frontend:9349a2a
          ports:
            - containerPort: 3000
          env:
            # ВАЖНО: фронт должен стучаться в gateway по DNS внутри кластера
            # Если в коде используешь NEXT_PUBLIC_API_URL — это оно.
            - name: NEXT_PUBLIC_API_URL
              value: "http://gateway-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: jumptotech-dev
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000