apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jumptotech-ingress
  namespace: jumptotech-dev
spec:
  ingressClassName: nginx
  rules:
    - host: jumptotech.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000